### ISSUE TITLE
Issue when refreshing  Userhouse page and other issues revolving logout

### ISSUE THREAD

**Issue by Haseebzz** [Haseebzz/Booking-app#17]
I have an issue when you refresh the userhouse page the username disappears and you have to click on another page in order to retrieve it back. Also @sritarung had an issue revolving around this too but his problem was it logouts the user if they refresh the userhouse page and the website becomes glitchy.

**Comment by sritarung** [comment]
Yes. There seems to be a glitch or an issue with the user interface as it seems to be logging me off after repeated clicking on browse. The name on account also disappears and appears with the issue.

**Comment by Charptr0** [comment]
> Yes. There seems to be a glitch or an issue with the user interface as it seems to be logging me off after repeated clicking on browse. The name on account also disappears and appears with the issue.

This may be the issue of your access and refresh tokens time limit is set too low as shown in the `.env` file. Try increase the time limit

From this
```
# secrets and keys
JWT_ACCESS_TOKEN_TIME=10s
JWT_REFRESH_TOKEN_TIME=30s
```

To this
```
# secrets and keys
JWT_ACCESS_TOKEN_TIME=10m
JWT_REFRESH_TOKEN_TIME=30m
```

So instead of having to tokens to be invalided for 30 seconds, it will be valid for 30 minutes instead. Long enough for you to go and test the app

**Comment by Charptr0** [comment]
> I have an issue when you refresh the userhouse page the username disappears and you have to click on another page in order to retrieve it back. 

I tried it on my end with the latest changes on the `master` branch, I can not successfully reproduce the bug.

**Comment by Haseebzz** [comment]
Switching to the main branch fixes the refresh issue of the username, but there are still other bugs involved.
